### PR TITLE
got the listing form data to send to mysql. yay the routes work

### PR DESCRIPTION
**Pull request by steppinonland**
the backend routes for the listing form were established. a lot of this work was just building off of what we built in the items route and model. we had to copy how we built the item route, model, and the axios request to make the listings post. putting the code side by side helped the post request be successful

Controller/Route:
Listings Controller code

Axios:
Listings Axios call

### CODE REVIEW

**Comment by steppinonland** [comment]
closes issue #20

**Comment by steppinonland** [comment]
closes #20

**Review by Steve-Munoz — APPROVED** [review]
noice!!!

**Review by julietg19 — APPROVED** [review]

**Review by adrian-palacios — APPROVED** [review]
great work team

**Pull request merged**
